require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :disable_input_output_paths => true

target 'BasicApp' do
  config = use_native_modules!
  pod 'react-native-mapbox-navigation', :path => '../../', :inhibit_warnings => false
  $ReactNativeMapboxGLIOSVersion = '~> 8.5.0'

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pre_install do |installer|
    $RNMBNAV.pre_install(installer)
  end

  target 'BasicAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |bc|
          bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
    # $RNMBNAV.post_install(installer)
    $RNMBNAV.pre_install(installer)
  end
end
